In [1]:
import pandas
import sklearn
import numpy
from sklearn.model_selection import KFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import scale
data = pandas.read_csv('wine.data', header = None)

In [2]:
y = data[0]
X = data.loc[:, 1:]

In [3]:
kf = KFold(n_splits = 5, shuffle=True,random_state=42)

In [4]:
kf.split(X,y)

<generator object _BaseKFold.split at 0x0000027342ECD750>

In [5]:
scores = []
for i in range(1,51):
    knn = KNeighborsClassifier(n_neighbors = i)
    scores.append(cross_val_score(knn, X, y, cv=kf))
scores    

[array([0.77777778, 0.66666667, 0.72222222, 0.71428571, 0.77142857]),
 array([0.72222222, 0.63888889, 0.69444444, 0.57142857, 0.68571429]),
 array([0.80555556, 0.61111111, 0.63888889, 0.65714286, 0.82857143]),
 array([0.75      , 0.52777778, 0.61111111, 0.65714286, 0.74285714]),
 array([0.72222222, 0.61111111, 0.61111111, 0.68571429, 0.74285714]),
 array([0.72222222, 0.63888889, 0.63888889, 0.68571429, 0.68571429]),
 array([0.69444444, 0.58333333, 0.72222222, 0.68571429, 0.71428571]),
 array([0.72222222, 0.61111111, 0.66666667, 0.65714286, 0.74285714]),
 array([0.72222222, 0.63888889, 0.72222222, 0.68571429, 0.74285714]),
 array([0.72222222, 0.61111111, 0.63888889, 0.68571429, 0.74285714]),
 array([0.75      , 0.63888889, 0.66666667, 0.71428571, 0.74285714]),
 array([0.72222222, 0.66666667, 0.69444444, 0.68571429, 0.71428571]),
 array([0.72222222, 0.69444444, 0.66666667, 0.65714286, 0.71428571]),
 array([0.72222222, 0.66666667, 0.72222222, 0.6       , 0.68571429]),
 array([0.75      , 

In [6]:
means = numpy.mean(scores,axis = 1)

In [8]:
pandas.DataFrame(scores, range(1, 51)).mean(axis=1).sort_values(ascending=False)

1     0.730476
35    0.724603
34    0.724603
48    0.719048
36    0.713492
29    0.713492
32    0.713492
33    0.713492
41    0.713492
38    0.713492
37    0.713492
3     0.708254
28    0.707937
30    0.707937
39    0.707937
50    0.707778
40    0.707778
43    0.707778
44    0.707778
45    0.707778
46    0.707778
42    0.707778
24    0.707619
11    0.702540
9     0.702381
23    0.702063
15    0.701905
21    0.701905
25    0.701905
17    0.701587
47    0.696667
12    0.696667
49    0.696667
26    0.696508
22    0.696508
27    0.696349
31    0.690952
13    0.690952
20    0.690952
10    0.680159
7     0.680000
8     0.680000
16    0.679524
18    0.679524
14    0.679365
19    0.679365
5     0.674603
6     0.674286
2     0.662540
4     0.657778
dtype: float64

In [11]:
scores2 = []

for i in range(1,51):
    knn = KNeighborsClassifier(n_neighbors = i)
    scores2.append(cross_val_score(knn, scale(X), y, cv=kf))
scores2    


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """


[array([0.94444444, 0.94444444, 0.91666667, 0.97142857, 0.94285714]),
 array([0.94444444, 0.88888889, 0.91666667, 0.97142857, 0.94285714]),
 array([0.94444444, 0.94444444, 0.97222222, 0.97142857, 0.94285714]),
 array([0.94444444, 0.91666667, 0.94444444, 0.94285714, 0.94285714]),
 array([0.94444444, 0.94444444, 0.97222222, 0.91428571, 0.97142857]),
 array([0.94444444, 0.91666667, 0.97222222, 0.97142857, 0.94285714]),
 array([0.94444444, 0.91666667, 0.97222222, 0.94285714, 0.97142857]),
 array([0.94444444, 0.91666667, 0.97222222, 0.97142857, 0.97142857]),
 array([0.94444444, 0.94444444, 0.97222222, 0.94285714, 1.        ]),
 array([0.94444444, 0.94444444, 0.97222222, 0.97142857, 0.97142857]),
 array([0.94444444, 0.94444444, 0.94444444, 0.97142857, 1.        ]),
 array([0.97222222, 0.91666667, 0.94444444, 0.97142857, 0.97142857]),
 array([0.94444444, 0.94444444, 0.94444444, 0.91428571, 1.        ]),
 array([0.97222222, 0.94444444, 0.97222222, 0.97142857, 0.97142857]),
 array([0.97222222, 

In [13]:
pandas.DataFrame(scores2, range(1, 51)).mean(axis=1).sort_values(ascending=False)

29    0.977619
16    0.972063
15    0.972063
18    0.966508
17    0.966508
20    0.966508
22    0.966508
14    0.966349
28    0.966349
33    0.966349
34    0.966349
43    0.966349
41    0.966349
45    0.966349
21    0.960952
11    0.960952
23    0.960952
38    0.960794
9     0.960794
10    0.960794
26    0.960794
39    0.960794
42    0.960794
30    0.960794
32    0.960794
40    0.960794
35    0.960794
36    0.960794
44    0.960635
50    0.960635
19    0.955397
12    0.955238
8     0.955238
25    0.955238
24    0.955238
27    0.955238
31    0.955238
37    0.955238
49    0.955079
47    0.955079
3     0.955079
46    0.949524
48    0.949524
7     0.949524
6     0.949524
13    0.949524
5     0.949365
1     0.943968
4     0.938254
2     0.932857
dtype: float64

In [60]:
import sklearn.datasets
b = sklearn.datasets.load_boston()
X = b.data
y = b.target
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [61]:
X = scale(X)

In [62]:
p = numpy.linspace(1,10,200)

In [63]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors = 5, weights = 'distance',metric = 'minkowski', p = 5)

In [64]:
cross_val_score(knn, X, y, cv=kf,scoring='neg_mean_squared_error')

array([-19.38682375, -17.01103269, -22.15189604, -19.90670903,
       -20.32384263])

In [65]:
maxes = -100
index = -1
for p in numpy.linspace(1,10,200):
    knn = KNeighborsRegressor(n_neighbors = 5, weights = 'distance',metric = 'minkowski', p = p)
    score = numpy.mean(cross_val_score(knn, X, y, cv=kf,scoring='neg_mean_squared_error'))
    print(maxes, score,p)
    if score > maxes:
        print(maxes, score,p)
        maxes = score
        index = p
print('score',maxes,'index',index)

-100 -16.030646734221644 1.0
-100 -16.030646734221644 1.0
-16.030646734221644 -16.40783870832999 1.0452261306532664
-16.030646734221644 -16.370696947059045 1.0904522613065326
-16.030646734221644 -16.445716308439433 1.135678391959799
-16.030646734221644 -16.475057773399403 1.1809045226130652
-16.030646734221644 -16.526432329318258 1.2261306532663316
-16.030646734221644 -16.636709345898257 1.271356783919598
-16.030646734221644 -16.82422425426731 1.3165829145728645
-16.030646734221644 -16.874209056598744 1.3618090452261307
-16.030646734221644 -17.124898819792115 1.4070351758793969
-16.030646734221644 -17.145231882153887 1.4522613065326633
-16.030646734221644 -17.01936008026763 1.4974874371859297
-16.030646734221644 -17.09913173771377 1.542713567839196
-16.030646734221644 -16.801326640288362 1.5879396984924623
-16.030646734221644 -16.980745198189776 1.6331658291457287
-16.030646734221644 -17.03345890364771 1.678391959798995
-16.030646734221644 -17.17164190266228 1.7236180904522613
-16.0306

-16.030646734221644 -21.013081934167804 7.5125628140703515
-16.030646734221644 -21.0148340985596 7.557788944723618
-16.030646734221644 -21.017417638850496 7.603015075376884
-16.030646734221644 -21.01086496090104 7.648241206030151
-16.030646734221644 -21.029703207238985 7.693467336683417
-16.030646734221644 -21.02242241833668 7.738693467336684
-16.030646734221644 -21.02402904696275 7.78391959798995
-16.030646734221644 -21.057853494649535 7.8291457286432165
-16.030646734221644 -21.0656423085044 7.874371859296483
-16.030646734221644 -21.06698490725231 7.919597989949749
-16.030646734221644 -21.068482443357823 7.964824120603016
-16.030646734221644 -21.06818327983064 8.010050251256281
-16.030646734221644 -21.071034728064937 8.055276381909547
-16.030646734221644 -21.02558771191022 8.100502512562814
-16.030646734221644 -20.95110250575009 8.145728643216081
-16.030646734221644 -20.996152778095716 8.190954773869347
-16.030646734221644 -20.892731816562325 8.236180904522612
-16.030646734221644 -20.

In [94]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [87]:
data = pandas.read_csv('perceptron-train.csv', header = None)

In [88]:
X_train = data.loc[:,1:]
y_train = data[0]

In [89]:
data = pandas.read_csv('perceptron-test.csv', header = None)
X_test = data.loc[:,1:]
y_test = data[0]

In [95]:
clf = Perceptron(random_state = 241)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
accuracy_score(y_test, predictions)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


0.655

In [98]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [99]:
clf.fit(X_train_scaled,y_train)
predictions2 = clf.predict(X_test_scaled)
accuracy_score(y_test, predictions2)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


0.845

In [100]:
0.845-0.655


0.18999999999999995